version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Varshini@20
      MYSQL_DATABASE: task
      MYSQL_USER: Varshini
      MYSQL_PASSWORD: mypassword
    ports:
      - "3300:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: task-management
    depends_on:
      - mysql
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task
      SPRING_DATASOURCE_USERNAME: Varshini
      SPRING_DATASOURCE_PASSWORD: mypassword
volumes:
  mysql-data: